### ISSUE TITLE
ROS Nav Stack with Ackermann Steering

### ISSUE THREAD

**Issue by karanchawla** [grassjelly/linorobot_ackermann#1]
Hello,

This is more of a question as opposed to an issue with the source. I notice you're using the default nav_stack provided by ROS for a robot with ackermann steering. How well does it perform? Since it only supports holonomic/differential drive robots, I'm interested in knowing the performance of the Navigation stack. 

Thanks.

**Comment by grassjelly** [comment]
Hi,

Can you post the question here: https://groups.google.com/forum/m/#!forum/linorobot
so the rest of the users can see in the future?

Thank you!
